import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/global.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { WalletContextProvider } from "@/components/walletProvider";
import '@solana/wallet-adapter-react-ui/styles.css';
import { BufferProvider } from '../components/bufferProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <BufferProvider>
          <Toaster containerStyle={{
            top: '90px'
          }} />
          <WalletContextProvider>
            <Header />
            {children}
            <Footer />
          </WalletContextProvider>
        </BufferProvider>
      </body>
    </html>
  );
}
